#!/bin/bash

# Binary LED counter for Raspberry Pi
#
# Copyright 2012 Luke Sandell <lasandell@gmail.com>
# Distributed under the Boost Software License, Version 1.0
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)

DELAY=1
PORTS=(0 1 4 7 8 9 10 11 14 15 17 18 21 22 23 24 27)
# Uncomment the following line for Raspberry Pi Revision 2
# PORTS=(2 3 4 7 8 9 10 11 14 15 17 18 22 23 24 25 27)

# Include gpio script to access the gpio function directly
source ./gpio

# Set all ports to output mode
for PORT in ${PORTS[@]}; do
	gpio $PORT mode out
	gpio $PORT write 0
done

PORT_COUNT=${#PORTS[@]}

# Count until CTRL-C is pressed
while true; do
	for((COUNTER = 0; COUNTER < 2 ^ PORT_COUNT; COUNTER++)); do
		REMAINDER=$COUNTER
		for((INDEX = PORT_COUNT - 1; INDEX >= 0; INDEX--)); do
			VALUE=$((2 ** INDEX))
			DIGIT=$((REMAINDER / VALUE))
			REMAINDER=$((REMAINDER - (VALUE * DIGIT)))
			gpio ${PORTS[INDEX]} write $DIGIT
		done
		sleep $DELAY
	done
done
